// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/gRPCExample.proto

package protofiles

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserData struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age" json:"age,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_gRPCExample_23229111a0eaecbe, []int{0}
}
func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (dst *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(dst, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CheckAgeRequest struct {
	Data                 *UserData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckAgeRequest) Reset()         { *m = CheckAgeRequest{} }
func (m *CheckAgeRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAgeRequest) ProtoMessage()    {}
func (*CheckAgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gRPCExample_23229111a0eaecbe, []int{1}
}
func (m *CheckAgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAgeRequest.Unmarshal(m, b)
}
func (m *CheckAgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAgeRequest.Marshal(b, m, deterministic)
}
func (dst *CheckAgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAgeRequest.Merge(dst, src)
}
func (m *CheckAgeRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAgeRequest.Size(m)
}
func (m *CheckAgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAgeRequest proto.InternalMessageInfo

func (m *CheckAgeRequest) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CheckAgeResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAgeResponse) Reset()         { *m = CheckAgeResponse{} }
func (m *CheckAgeResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAgeResponse) ProtoMessage()    {}
func (*CheckAgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gRPCExample_23229111a0eaecbe, []int{2}
}
func (m *CheckAgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAgeResponse.Unmarshal(m, b)
}
func (m *CheckAgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAgeResponse.Marshal(b, m, deterministic)
}
func (dst *CheckAgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAgeResponse.Merge(dst, src)
}
func (m *CheckAgeResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAgeResponse.Size(m)
}
func (m *CheckAgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAgeResponse proto.InternalMessageInfo

func (m *CheckAgeResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*UserData)(nil), "protofiles.UserData")
	proto.RegisterType((*CheckAgeRequest)(nil), "protofiles.CheckAgeRequest")
	proto.RegisterType((*CheckAgeResponse)(nil), "protofiles.CheckAgeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgeCheckerClient is the client API for AgeChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgeCheckerClient interface {
	CheckAge(ctx context.Context, in *CheckAgeRequest, opts ...grpc.CallOption) (*CheckAgeResponse, error)
}

type ageCheckerClient struct {
	cc *grpc.ClientConn
}

func NewAgeCheckerClient(cc *grpc.ClientConn) AgeCheckerClient {
	return &ageCheckerClient{cc}
}

func (c *ageCheckerClient) CheckAge(ctx context.Context, in *CheckAgeRequest, opts ...grpc.CallOption) (*CheckAgeResponse, error) {
	out := new(CheckAgeResponse)
	err := c.cc.Invoke(ctx, "/protofiles.AgeChecker/CheckAge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgeCheckerServer is the server API for AgeChecker service.
type AgeCheckerServer interface {
	CheckAge(context.Context, *CheckAgeRequest) (*CheckAgeResponse, error)
}

func RegisterAgeCheckerServer(s *grpc.Server, srv AgeCheckerServer) {
	s.RegisterService(&_AgeChecker_serviceDesc, srv)
}

func _AgeChecker_CheckAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgeCheckerServer).CheckAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.AgeChecker/CheckAge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgeCheckerServer).CheckAge(ctx, req.(*CheckAgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgeChecker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.AgeChecker",
	HandlerType: (*AgeCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAge",
			Handler:    _AgeChecker_CheckAge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/gRPCExample.proto",
}

func init() {
	proto.RegisterFile("protofiles/gRPCExample.proto", fileDescriptor_gRPCExample_23229111a0eaecbe)
}

var fileDescriptor_gRPCExample_23229111a0eaecbe = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x4f, 0x0f, 0x0a, 0x70, 0x76, 0xad, 0x48, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x03, 0x0b, 0x0b, 0xb1, 0xe4, 0x26, 0x66, 0xe6, 0x29, 0x19, 0x70, 0x71, 0x84,
	0x16, 0xa7, 0x16, 0xb9, 0x24, 0x96, 0x24, 0x0a, 0x09, 0x70, 0x31, 0x27, 0xa6, 0xa7, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x29, 0x17, 0xbf, 0x73, 0x46, 0x6a, 0x72,
	0xb6, 0x63, 0x7a, 0x6a, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x12, 0x17, 0x4b, 0x4a,
	0x62, 0x49, 0x22, 0x58, 0x27, 0xb7, 0x11, 0x9f, 0x1e, 0xc8, 0x64, 0x3d, 0x98, 0xb1, 0x41, 0x60,
	0x39, 0x25, 0x2d, 0x2e, 0x01, 0x84, 0xb6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e,
	0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xb0, 0x4e, 0xce, 0x20, 0x28, 0xcf, 0xc8, 0x93, 0x8b,
	0xcb, 0x31, 0x3d, 0x15, 0xac, 0x3c, 0xb5, 0x48, 0xc8, 0x9a, 0x8b, 0x03, 0xa6, 0x53, 0x48, 0x14,
	0x62, 0x36, 0x9a, 0x03, 0xa4, 0xc4, 0xd0, 0x85, 0x21, 0x16, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x3d,
	0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x2e, 0x55, 0xeb, 0x0c, 0x01, 0x00, 0x00,
}
